name: Continuous Deployment Workflow

on:
    push:
        branches: 
            - 'main'
        paths: 
            - 'web/**'
    
    workflow_dispatch:
    

defaults:
    run:
        shell: bash
        working-directory: ./web


jobs:
    deploy_saging:
        environment: stagind
        name: Deploy to staging
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              name: 'Checkout reppsitory'

            - name: rsync deployment to staging env
              uses: burnett01/rsync-deployments@23a557dceb19f9bb960ef40cf75cab5e9b37ec1f
              with:
                switches: -avzr --delete
                path: ./web
                remote_path: /var/app
                remote_host: ${{ secrets.HOSTNAME }}
                remote_user: ${{ secrets.USER }}
                remote_key: ${{ secrets.KEY }}

            - uses: JimCronqvist/action-ssh@7737f1192ddd8376686e9d6354dea44592c942bf
              name: Execute ssh command on remote server
              with:
                hosts: '${{ secrets.USER }}@${{ secrets.HOSTNAME }}'
                privateKey: ${{ secrets.KEY }}
                command: |
                  cd /var/app/web
                  npm ci
                  pm2 start /var/app/web/bin/www || pm2 restart /var/app/web/bin/www 
                  sudo service nginx restar
