name: Continious integrations for node app

on:
  push:
    branches:
      - main
    paths:
      - './web/**'
  pull_request:
    branches:
      - main
    paths:
      - 'web/**'
  workflow_dispatch: 


jobs:
  test:
    name: 'Run tests'
    defaults:
      run:
        shell: bash
        working-directory: './web/'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: 'Copy code from repository'
      
      - name: 'Istall dependencies'
        run: npm install

      - name: 'Run tests'
        run: npm run test

  lint:
    name: 'Linting code'
    defaults:
      run:
        shell: bash
        working-directory: './web/'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: 'Copy code from repo'

      - name: 'Install dendencies'
        run: npm install

      - name: 'Run lint'
        run: npx standard -v


